# Zettelschrift Native Specification - 1.0.0
# Written as a Parsing Expression Grammar (PEG). Attribution functions are not described here, and are implemented in the Zettelschrift Native Parser

ZettelschriftFile <- Node* !.
Node <- Address Content
Address <- "@" Nodeseq Newline SecondaryAddress* Newline
SecondaryAddress <- Nodeseq Newline / PlainTitle Newline
Content <- ( Reference / Node / FreeContent )*
Reference <- Append? ReferenceTarget / Append Nodesect / Newline Nodesect 
Append <- "%" Content "%" " "
Nodesect <- "@(" PlanTitle ")" (" " ReferenceTarget)?
ReferenceTarget <- "[[" ( Reference / Nodeseq / PlainTitle / Nodesect) ( "::" ( Reference / Nodeseq / PlainTitle / Nodesect ) )* "]]"
FreeContent <- !(Newline Address) .
Nodeseq <- ( PlainTitle "/" )* PlainTitle
PlainTitle <- ( !"(" !("@" / "[[" / "]]" / "::" / "/" / Newline ) !")" . )+
Newline <- "\r\n" / "\n" / "\r"

# Zettelschrift © 2026 by Jayu Eleuthéria is licensed under Creative Commons Attribution-ShareAlike 4.0 International. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/
